### ISSUE TITLE
 Max retries exceeded

### ISSUE THREAD

**Issue by zzsuneo** [gfhuertac/maka#5]
when i run this code some hours later ,it error:

Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:/car/maka/samples/author.py", line 57, in querier_enclosure
    results = query.post()
  File "D:\car\maka\inquirer.py", line 406, in post
    the_request = requests.post(url, data=data, headers=headers)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\requests\api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\requests\api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\requests\sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "D:\ProgramData\Anaconda3\envs\tensorflow\lib\site-packages\requests\adapters.py", line 502, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='api.labs.cognitive.microsoft.com', port=443): Max retries exceeded with url: /academic/v1.0/evaluate (Caused by ProxyError('Cannot connect to proxy.', RemoteDisconnected('Remote end closed connection without response',)))

sometimes  it could run and give me the right data,  could u give me some advice, thanks.

**Comment by gfhuertac** [comment]
It seems to be a network problem.
Can you check, from postman or similar, that https://api.labs.cognitive.microsoft.com/academic/v1.0/evaluate works when you receive that message?
